### ISSUE TITLE
Task: testing 5K-node cluster with three partitioned API Servers

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#572] opened 2020-08-12 00:24 UTC
**What would you like to be added**:

**Why is this needed**:

**Comment by sonyafenge** [comment] 2020-08-13 20:11
5000 nodes run for 3 apiserver failed with error below. workaround has be applied and rerun in progress:
```
E0813 02:02:00.315043    4894 test_metrics.go:217] TestMetrics: [action gather failed for EtcdMetrics measurement: unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider kubemark: 'error reading SSH key /home/sonyali/.ssh/google_compute_engine: 'open /home/sonyali/.ssh/google_compute_engine: too many open files''"}]
I0813 02:02:00.315087    4894 simple_test_executor.go:162] Step "Collecting measurements" ended
W0813 02:02:00.315094    4894 simple_test_executor.go:165] Got errors during step execution: [measurement call TestMetrics - TestMetrics error: [action gather failed for EtcdMetrics measurement: unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting signer for provider kubemark: 'error reading SSH key /home/sonyali/.ssh/google_compute_engine: 'open /home/sonyali/.ssh/google_compute_engine: too many open files''"}]]
```

**Comment by sonyafenge** [comment] 2020-08-14 17:57
8/13/2020 update:

1. Too many opened files issue fixed after update ulimit -n to 65535
2. Density/config.yaml run successfully but still have time out error.
3. Load/config.yaml run failed with kube-scheduler, etcd, kube-apiserver crash.    I will restart another run with Xiaoning’s fix
4. Throughput looks good:
```
{
  "perc50": 20,
  "perc90": 20.4,
  "perc99": 24.2,
  "max": 33.8
}
 ```


```
commit 24422cc496afbf2698db27c277c1cf443abafb74
```

**Comment by sonyafenge** [comment] 2020-08-17 17:28
Another a 5000 nodes run with 3 api, 1 workload, 1 etcd finished during weekend.
Density run completed with timeout issue and also high podstart latency issue, but still has test result. 
Load run failed with a panic in perf-test tools  related apimachinery.
```
panic: send on closed channel
 
goroutine 957017 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*AggregatedWatcher).AddWatchInterface.func1(0x1a99600, 0xc056b75880, 0xc06afed580, 0xc056b75900)
        /home/sonyali/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/watch.go:149 +0x1e9
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*AggregatedWatcher).AddWatchInterface
        /home/sonyali/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/watch.go:134 +0xeb
```
All logs are at sonyadev3: /home/sonyali/logs/perf-test/gce-5000/arktos/0814api3-wc1-etcd1 under workload-controller-manager GCP project.

**Comment by sonyafenge** [comment] 2020-08-17 17:32
08/14. [perf-tests][arktos][node5000] 1api-1wc-1etcd
load testing failed with a runtime panic, All logs are at sonyadev2:/home/sonyali/logs/perf-test/gce-5000/arktos/0814api1-wc1-etcd1/logs/ending under workload-controller-manager
 
 ```
E0815 05:05:52.441500       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E0815 05:05:52.441527       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E0815 05:05:52.441621       1 runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because
 serving request timed out and response had been started)
goroutine 536233 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x396afc0, 0xc0006d45a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc4d6373ce0, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x396afc0, 0xc0006d45a0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc4ce585b20, 0xc4ce40cb40)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:238 +0x1a9
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc03eb419e0, 0x76ffe80, 0xc4d2996690, 0xc4ce58da00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:122 +0x2ab
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x76ffe80, 0xc4d2996690, 0xc4ce58d900)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xf3
net/http.HandlerFunc.ServeHTTP(0xc024596f60, 0x76ffe80, 0xc4d2996690, 0xc4ce58d900)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x76ffe80, 0xc4d2996690, 0xc4cbbfa500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x2b8
net/http.HandlerFunc.ServeHTTP(0xc024597260, 0x76ffe80, 0xc4d2996690, 0xc4cbbfa500)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x76ffe80, 0xc4d2996690, 0xc4cbbfa500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x127
net/http.HandlerFunc.ServeHTTP(0xc03eb41a00, 0x76f3e80, 0xc18c4f64f0, 0xc4cbbfa500)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc0245974a0, 0x76f3e80, 0xc18c4f64f0, 0xc4cbbfa500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc01e2352b0, 0x76f3e80, 0xc18c4f64f0, 0xc4cbbfa500)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc05cf06a80, 0xc01e2352b0, 0x76f3e80, 0xc18c4f64f0, 0xc4cbbfa500)
        /usr/local/go/src/net/http/server.go:3323 +0x8d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc1833b9380, 0xc18c4f64f0, 0xc4cbbfa500, 0xc4cb77eca0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2095 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1829 +0x4f4
I0815 05:05:52.441741       1 wrap.go:47] GET /api/v1/services?labelSelector=%21service.kubernetes.io%2Fservice-proxy-name&limit=500&resourceVersion=0: (15.18913715s) 200 [kubemark/v2.7.4 (linux/amd64) kubernetes
/22d7f2d 104.196.114.83:3472]
F0815 05:05:52.441798       1 controller.go:165] Unable to perform initial service nodePort check: unable to refresh the port block: Unexpected error when reading response body. Please retry. Original error: http
2: server sent GOAWAY and closed the connection; LastStreamID=279, ErrCode=NO_ERROR, debug=""
```

```
commit 22d7f2de04691ccdd0ec2d1a29e615756e94ea63
```

**Comment by sonyafenge** [comment] 2020-08-18 19:58
all node5000 perf-tests run recently has too high latency 99th percentile error:
               
Errors: [measurement call WaitForControlledPodsRunning - WaitForRunningSaturationDeployments error: 3 objects timed out: Deployments: rrxp9q-testns/saturation-deployment-0, oj6uj5-testns/saturation-deployment-0, wbn2xs-testns/saturation-deployment-0
measurement call PodStartupLatency - PodStartupLatency error: pod startup: too high latency 99th percentile: got 5.453821139s expected: 5s]
 
per community SLIs/SLOs, resource latency for 99th percentile need <= 5s

I took some time to investigate this issue and found one community mentioned downgrade log-level from v4 to v2 will improve the pod latency. I will start another run to verify this. We have kubemark log level default set is V4 for all testing.

**Comment by sonyafenge** [comment] 2020-08-19 17:58
08/18. [perf-tests][arktos][node5000]3api-2wc-1etcd perf-test
Start another run yesterday with log-level=2, got density run successfully and pods latency error gone. But load testing failed with two panic:
In kubelet:  panic: send on closed channel.  Happened also in previous run, @Ying Huang is checking.
In kube-apiserver: Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started),  @Peng Du is checking.
 
Here is the detailed pod latency that I got for yesterday’s run, our 5000 nodes results even are a little bit better than community 500 nodes for pod_startup, run_to_watch.

Item | unit | Perc50 | Perc90 | Perc99
-- | -- | -- | -- | --
create_to_schedule | ms | 0 | 0 | 1000
pod_startup | ms | 1837.67419 | 2593.85902 | 3341.00736
run_to_watch | ms | 1084.9273 | 1831.74182 | 2216.77722
schedule_to_run | ms | 1000 | 1000 | 1000
schedule_to_watch | ms | 1808.51779 | 2541.25413 | 3041.89269

**Comment by pdgetrf** [comment] 2020-08-19 19:23
regarding the panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)

![image](https://user-images.githubusercontent.com/252020/90680201-59aeb080-e216-11ea-8e0e-d9004aff1ba6.png)
![image](https://user-images.githubusercontent.com/252020/90680266-721ecb00-e216-11ea-9e51-c19d441fbce6.png)

And etcd.log has lots of warning like this:

![image](https://user-images.githubusercontent.com/252020/90680490-c32ebf00-e216-11ea-9566-19cb7f2463a9.png)

Here's some info on what this warning means:

https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-apply-entries-took-too-long-mean

**Comment by pdgetrf** [comment] 2020-08-20 18:11
based on this: https://medium.com/@aatarasoff/how-we-hack-densely-packed-gke-cluster-ccbc4b2848e6

we need to check the control plane pods resource allocation in the yaml file. 

@sonyafenge  where can I find the manifest file for apiserver that was used in this run?

**Comment by sonyafenge** [comment] 2020-08-20 19:13
@pdgetrf, here is source code: https://github.com/futurewei-cloud/arktos/blob/master/cluster/gce/manifests/kube-apiserver.manifest

and here is one run time example from master
[kube-apiserver.manifest.log](https://github.com/futurewei-cloud/arktos/files/5105023/kube-apiserver.manifest.log)

:

**Comment by pdgetrf** [comment] 2020-08-20 19:47
```yaml
"containers":[
    {
    "name": "kube-apiserver",
    "image": "{{pillar['kube_docker_registry']}}/kube-apiserver:{{pillar['kube-apiserver_docker_tag']}}",
    "resources": {
      "requests": {
        "cpu": "250m"
      }
    }
```

this **_**"cpu": "250m"**_** is a bit concerning.

**Comment by pdgetrf** [comment] 2020-08-20 19:53
https://github.com/kubernetes/kubernetes/issues/74302 reported a similar case where patching node status failed. his solution is to set --http2-max-streams-per-connection to 1000

**Comment by sonyafenge** [comment] 2020-08-20 21:03
just checked kube-up script, all ETCD data is in master-pd, which is SSD. 
in ./cluster/gce/gci/configure-helper-common.sh
```
echo "Mounting master-pd"
  local -r pd_path="/dev/disk/by-id/google-master-pd"
  local -r mount_point="/mnt/disks/master-pd"
  # Format and mount the disk, create directories on it for all of the master's
  # persistent data, and link them to where they're used.
  mkdir -p "${mount_point}"
  safe-format-and-mount "${pd_path}" "${mount_point}"
  echo "Mounted master-pd '${pd_path}' at '${mount_point}'"

  # NOTE: These locations on the PD store persistent data, so to maintain
  # upgradeability, these locations should not change.  If they do, take care
  # to maintain a migration path from these locations to whatever new
  # locations.

  # Contains all the data stored in etcd.
  mkdir -m 700 -p "${mount_point}/var/etcd"
  ln -s -f "${mount_point}/var/etcd" /var/etcd
```
```
# Replace the volume host path.
  sed -i -e "s@/mnt/master-pd/var/etcd@/mnt/disks/master-pd/var/etcd@g" "${temp_file}"
```

**Comment by sonyafenge** [comment] 2020-08-24 18:05
8/24/2020 [perf-tests][arktos][node5000] node5000-1api-1wc-1etcd
started new run with —http2-max-streams-per-connection=1000 when start apiserver, still get this panic error when run load testing
```
E0822 10:25:44.076271       1 runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
```

and also get another repro in density result, this error was fixed after change log level to 2, not sure if this repro related with "http2-max-streams-per-connection" 
```
 Errors: [measurement call PodStartupLatency - PodStartupLatency error: pod startup: too high latency 99th percentile: got 6.797502554s expected: 5s]
```

**Comment by pdgetrf** [comment] 2020-08-24 18:09
> 8/24/2020 [perf-tests][arktos][node5000] node5000-1api-1wc-1etcd
> started new run with —http2-max-streams-per-connection=1000 when start apiserver, still get this panic error when run load testing
> 
> ```
> E0822 10:25:44.076271       1 runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
> ```
> 
> and also get another repro in density result, this error was fixed after change log level to 2, not sure if this repro related with "http2-max-streams-per-connection"
> 
> ```
>  Errors: [measurement call PodStartupLatency - PodStartupLatency error: pod startup: too high latency 99th percentile: got 6.797502554s expected: 5s]
> ```

where's the full log?

also not sure what this means " also get another repro in density result, this error was fixed after change log level to 2" are we getting the error or not?

**Comment by sonyafenge** [comment] 2020-08-24 18:14
> also not sure what this means " also get another repro in density result, this error was fixed after change log level to 2" are we getting the error or not?

we got "too high latency 99th percentile" issue fixed in previous run, but this time, it is reproed again. so possibly, the previous fix is not root cause, or this repro is caused by changing http2-max-streams-per-connection

**Comment by sonyafenge** [comment] 2020-08-24 18:18
> where's the full log?

sonya-useast1: /home/sonyali/logs/perf-test/gce-5000/arktos/0821-1api-1wc-1etcd under workload-controller-manager project

**Comment by pdgetrf** [comment] 2020-08-24 18:36
ETCD log is filled with these

![image](https://user-images.githubusercontent.com/252020/91082782-05cd0e80-e5fe-11ea-8dee-bc6d18058ba9.png)

**Comment by pdgetrf** [comment] 2020-08-24 18:37
we need to find a way to stress test etcd to make sure it's set up correctly.

**Comment by pdgetrf** [comment] 2020-08-24 19:24
etcd perf benchmarking tools https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#performance

I'm giving this a try for now on my cluster running 1.18.5

**Comment by sonyafenge** [comment] 2020-08-25 17:40
8/24/2020 [perf-tests][arktos][node5000] node5000-1api-1wc-1etcd:
1. Density failed with panic error, will start another run to verify why pod latency increased again after change log level to 2
```
Errors: [measurement call PodStartupLatency - PodStartupLatency error: pod startup: too high latency 99th percentile: got 6.615098138s expected: 5s]
```
2. Load run still failed and crashed with panic in apiserver: 
```
runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
```
3. All logs saved under workload-controller-manager project: 
sonya-useast1: /home/sonyali /logs/perf-test/gce-5000/arktos/0824-1api-1wc-1etcd/logs/crashed

**Comment by sonyafenge** [comment] 2020-08-26 20:44
08/26:[Perf-tests: arktos][node5000]too high latency 99th percentile
Started two run to verify “too high latency 99th percentile” and found:
1. Leader-elect has impact for pod start-up latency, but not too much. Two run with 3api-2wc-1etcd finished on 8/18 and 8/26 using same build:
       8/18: set Leader-elect= false and get pod start_up perc 99 value: 3341 ms
       8/26: remove Leader-elect= false from kube-controller-manager, get pods start_up perc 99 value: 4631 ms
Both in community SLO
2. Workload-controller-manager number may have big impact for pod start-up latency. Started two run 0824-1api-1wc-1etcd and 0825-3api-2wc-1etcd using same build
       8/24: only has 1 wc, get pod start_up perc 99 value: 6615 ms
       8/25: has 2 wc, get pod start_up perc 99 value: 3574 ms
3. Checked 5000 nodes run history and found runs with 1 wc, all failed with  “too high latency 99th percentile”

**Comment by Sindica** [comment] 2020-08-27 04:44
> 08/26:[Perf-tests: arktos][node5000]too high latency 99th percentile
> Started two run to verify “too high latency 99th percentile” and found:
> 
> 1. Leader-elect has impact for pod start-up latency, but not too much. Two run with 3api-2wc-1etcd finished on 8/18 and 8/26 using same build:
>    8/18: set Leader-elect= false and get pod start_up perc 99 value: 3341 ms
>    8/26: remove Leader-elect= false from kube-controller-manager, get pods start_up perc 99 value: 4631 ms
>    Both in community SLO
> 2. Workload-controller-manager number may have big impact for pod start-up latency. Started two run 0824-1api-1wc-1etcd and 0825-3api-2wc-1etcd using same build
>    8/24: only has 1 wc, get pod start_up perc 99 value: 6615 ms
>    8/25: has 2 wc, get pod start_up perc 99 value: 3574 ms
> 3. Checked 5000 nodes run history and found runs with 1 wc, all failed with  “too high latency 99th percentile”

It is strange that # of WC has impact on pod start up latency. It seems like includes waiting time during throttling.

**Comment by panda98004** [comment] 2020-09-03 20:42
Closed the task. There are individual tasks opened for each error.

**Closed by panda98004** 2020-09-03 20:42 UTC
