### ISSUE TITLE
Cannot create a pod by user context

### ISSUE THREAD

**Issue by ZongbaoLiu** [futurewei-cloud/arktos#423] opened 2020-06-28 02:48 UTC
**What happened**:
First, I create a tenant.
```
root@arktos:/home/arktos/test# kubectl create tenant tenant-1
setting storage cluster to system
tenant/tenant-1 created
root@arktos:/home/arktos/test# kubectl get tenant
NAME       STORAGEID   STATUS   AGE
system     system      Active   20s
tenant-1   system      Active   4s
```
Then, I setup user context by setup_client.sh.
```
root@arktos:/home/arktos/test# /root/go/src/github.com/arktos/hack/setup-multi-tenancy/setup_client.sh tenant-1 admin 127.0.0.1
setting up context tenant-1-admin-context for tenant-1/admin in group tenant-1-group at host 127.0.0.1
generating a client key tenant-1.key...
creating a sign request tenant-1.csr...
creating an tenant certificate tenant-1-admin.crt and get it signed by CA
Setting up tenant context...
cleaned up tenant-1.csr
***************************
Context has been setup for tenant tenant-1/admin in /var/run/kubernetes/admin.kubeconfig.

Use 'kubectl use-context tenant-1-admin-context' to set it as the default context

Here's an example on how to access cluster:

+ kubectl --context=tenant-1-admin-context get pods
No resources found.
```
I want to create a pod by user context, but failed.
```
root@arktos:/home/arktos/test# cat nginx-1.yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx-pod-1
  labels:
    name: nginx-container-1
spec:
  containers:
  - name: nginx-container-1
    image: nginx:1.7.9

root@arktos:/home/arktos/test# kubectl --context=tenant-1-admin-context create -f nginx-1.yaml
Error from server (Forbidden): unknown
```
I can create a pod by the command(--tenant), and I can also get the pod by user context.
```
root@arktos:/home/arktos/test# kubectl create -f nginx-1.yaml --tenant tenant-1
pod/nginx-pod-1 created

root@arktos:/home/arktos/test# kubectl --context=tenant-1-admin-context get pods
NAME          HASHKEY               READY   STATUS    RESTARTS   AGE
nginx-pod-1   8670374645759550569   1/1     Running   0          28s
```

**Environment**:
- Arktos version (use `kubectl version`):
```
root@arktos:/home/arktos/test# kubectl version
Client Version: version.Info{Major:"0", Minor:"2+", GitVersion:"v0.2-114+ab7a6cfcc4d501-dirty", GitCommit:"ab7a6cfcc4d501477f567ab38c9281c553ed6baf", GitTreeState:"dirty", BuildDate:"2020-06-28T02:20:49Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"0", Minor:"2+", GitVersion:"v0.2-114+ab7a6cfcc4d501-dirty", GitCommit:"ab7a6cfcc4d501477f567ab38c9281c553ed6baf", GitTreeState:"dirty", BuildDate:"2020-06-28T02:20:49Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
root@arktos:/home/arktos/test# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
root@arktos:/home/arktos/test# uname -a
Linux arktos 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pdgetrf** [comment] 2020-06-28 03:10
taking a look

**Comment by pdgetrf** [comment] 2020-06-28 03:29
I'm able to repro this.

root@ip-172-31-27-32:~/code/src/k8s.io/arktos/hack/setup-multi-tenancy# kubectl --context=tenant-1-admin-context create -f ~/code/src/k8s.io/arktos/test/yaml/vanilla.yaml
Error from server (Forbidden): unknown

**Comment by pdgetrf** [comment] 2020-06-28 03:30
using --tenant would work because it's create pod as the system tenant in the tenant-1 space.

**Comment by pdgetrf** [comment] 2020-06-28 03:35
the clusterrolebinding automatically provisioned when tenant is created is for user "admin":

![image](https://user-images.githubusercontent.com/252020/85937139-8cdb6000-b8b5-11ea-826a-c60b77796bc7.png)

while setup_client.sh is sets user to "${tenant}-${person}"

**Comment by pdgetrf** [comment] 2020-06-28 03:43
I0628 03:43:25.036688   18974 rbac.go:127] RBAC DENY: user "admin" groups ["tenant-1-group" "system:authenticated"] cannot "get" nonResourceURL "/openapi/v2" cluster-wide
I0628 03:43:25.037682   18974 rbac.go:127] RBAC DENY: user "admin" groups ["tenant-1-group" "system:authenticated"] cannot "get" nonResourceURL "/swagger-2.0.0.pb-v1" cluster-wide

**Comment by pdgetrf** [comment] 2020-06-28 04:13
I0628 04:10:18.116163   12534 rbac.go:127] RBAC DENY: user &{Name:system:anonymous UID: Groups:[system:unauthenticated] Extra:map[] Tenant:system}  cannot "get" nonResourceURL "/healthz" cluster-wide

**Comment by pdgetrf** [comment] 2020-06-28 04:15
I0628 04:14:31.424339   12534 rbac.go:127] RBAC DENY: user &{Name:admin UID: Groups:[tenant-1-group system:authenticated] Extra:map[] Tenant:tenant-1}  cannot "get" nonResourceURL "/openapi/v2" cluster-wide
I0628 04:14:31.424368   12534 authorization.go:74] Forbidden: "/openapi/v2?timeout=32s", Reason: ""

**Comment by pdgetrf** [comment] 2020-06-28 04:45
@ZongbaoLiu I've located the commit that caused this issue e8c1a21242c33ff3b159c62522ba9ae5d21c7e09

if you don't need the most recent code, please use code up to commit 20ae7ba1bc37497751d31726c3a852619ffd7d72.

I'm looking into the issue and fix. we could also roll back the change but if it doesn't block you at the moment I would like to root cause it and add fix.

**Comment by ZongbaoLiu** [comment] 2020-06-28 04:56
@pdgetrf ok, I will use code up to commit 20ae7ba.

**Comment by pdgetrf** [comment] 2020-06-28 06:44
fix PR is out for review

**Comment by pdgetrf** [comment] 2020-06-29 00:31
@ZongbaoLiu fix is merged into master. please verify.

**Comment by ZongbaoLiu** [comment] 2020-06-29 06:29
@pdgetrf It's OK, I have verified.

**Comment by pdgetrf** [comment] 2020-06-29 06:51
@pdgetrf great! closing issue.

**Closed by pdgetrf** 2020-06-29 06:51 UTC
Labels: Verifying, bug
