### ISSUE TITLE
Kubelet logs info: controller plane pod: kube-controller-manager hostname is truncated 

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#660] opened 2020-09-01 18:01 UTC
**What happened**:
```
Aug 30 22:02:31 node15000-3api-2wc-1etcd-kubemark-master kubelet[3342]: E0830 22:02:31.374046    3342 kubelet_pods.go:389] hostname for pod:"kube-controller-manager-node15000-3api-2wc-1etcd-kubemark-master" was longer than 63. Truncated hostname to :"kube-controller-manager-node15000-3api-2wc-1etcd-kubemark-maste"
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Logs are located under workload-controller-manger project at: sonya-useast1: /home/sonyali/logs/perf-test/gce-10000/arktos/0830-node15000-3api-2wc-1etcd/logs/crashed
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yb01** [comment] 2020-09-02 22:41
this is not a bug in Arktos. the max host name allowed in k8s is 63 chars. hence the node name is truncated to this size to this string: "kube-controller-manager-node15000-3api-2wc-1etcd-kubemark-maste"

when we name the perf runs, we should change our script to ensure the size of node.

**Comment by sonyafenge** [comment] 2020-09-02 23:19
ok, if this is the case, then we can use the smaller size node name

**Comment by yb01** [comment] 2020-09-02 23:21
Assign to Sonya for a fix in the perf run naming script

**Comment by sonyafenge** [comment] 2020-09-04 17:21
### 9/3/2020 [issuedebug][arktos][nsdelete] 
verified in this run with shorter size KUBE_GCE_INSTANCE_PREFIX=nsdelete-3a1w1e, cannot repro this issue.

**Comment by sonyafenge** [comment] 2020-09-04 17:25
### 9/3/2020 [issuedebug][arktos][ETCDperf]
verified in this run with shorter size KUBE_GCE_INSTANCE_PREFIX=etcd-3a1w1e , cannot repro this issue.

logs can be found under GCP project: workload-controller-manager:
```
sonya-uswest2:  /home/sonyali/logs/perf-test/gce-5000/arktos/0903-etcd-3a1w1e 
```

**Comment by panda98004** [comment] 2020-09-04 20:13
Close with workaround

**Closed by panda98004** 2020-09-04 20:13 UTC
